QR Code Generator(in real time)
PreyumKr/DailyLife_Problem_Solvers pull request #34
Opened 2024-10-18 16:36 UTC by Anuraj-IND

What I did?
Created a new folder which contain
- A .py file 
- A readme.md file
Also created :
- proper brief about this project in main readme.md file followed by same order 

just make sure to use that hacktoberfestaccepted tag and yea its my first time i tried live frame catching code it was a fun experience !

2024-10-18 16:42 UTC, PreyumKr requested changes
Create a single three hash title and put everything inside that in main readme. Look the readme that you create in preview mode to see how different you write the readme instructions. Also, put the files related to a project inside the project folder. You are using Github GUI or what? Even there its possible to cleanly add files inside a folder. Don't put things outside and keep the readme format as it is from the start. You know how # works for headers right?

2024-10-18 16:48 UTC, Anuraj-IND commented
> Create a single three hash title and put everything inside that in main readme. Look the readme that you create in preview mode to see how different you write the readme instructions. Also, put the files related to a project inside the project folder. You are using Github GUI or what? Even there its possible to cleanly add files inside a folder. Don't put things outside and keep the readme format as it is from the start. You know how # works for headers right?

oh ok wait ill use single hashes then fine and about that file its actually auto generated i havent created it i can specify path but then itll not work if someone will just clone and use it directly even tho I have given instructions how to specify path ill still just move the auto generated file in folder ok coz setting path might be cause trouble for new users whos directly running script after cloning
2 task 
- single hashes
- move auto generator file inside folder ok? or anything else i have to do

2024-10-18 16:54 UTC, Anuraj-IND commented
@PreyumKr done boss check it

2024-10-18 17:22 UTC, Anuraj-IND commented
@PreyumKr add hacktoberfestaccepted tag like you did in previous one i need that tag here too
![Screenshot 2024-10-18 211609](https://github.com/user-attachments/assets/e717d974-abd2-4088-85f1-80f307487dd4)

2024-10-19 11:09 UTC, PreyumKr requested changes
### QR Code Reader (In Real Time)

This project demonstrates a simple Python-based QR code scanner that works in real-time using a webcam. It uses the `OpenCV` and `Pyzbar` libraries to detect and decode QR codes live from a video stream and save the results to a text file.

`Overview`

The script captures video input from your webcam, detects QR codes in real-time, and prints the decoded data to the console. After successfully detecting a QR code, the data is appended to a text file and the camera closes automatically.

`Features`

- Real-time QR code detection using a webcam.
- Decodes and saves QR code data to a text file.
- Automatically shuts down the camera after successfully reading a QR code.
- Uses the `OpenCV` library for video capture and the `Pyzbar` library for QR code decoding.
- Supports various QR code formats.

* **Read** the ***readme.md*** given inside the folder and try it out ! ***:-)***


### Header
* point1
* point 2
* point 3
* point 4
*  point 5

Dont add any other header non header or any words in between and keep the points as it is that is using * no - no ` .

2024-10-19 11:10 UTC, Anuraj-IND commented
> ### QR Code Reader (In Real Time)
> 
> This project demonstrates a simple Python-based QR code scanner that works in real-time using a webcam. It uses the `OpenCV` and `Pyzbar` libraries to detect and decode QR codes live from a video stream and save the results to a text file.
> 
> `Overview`
> 
> The script captures video input from your webcam, detects QR codes in real-time, and prints the decoded data to the console. After successfully detecting a QR code, the data is appended to a text file and the camera closes automatically.
> 
> `Features`
> 
> - Real-time QR code detection using a webcam.
> - Decodes and saves QR code data to a text file.
> - Automatically shuts down the camera after successfully reading a QR code.
> - Uses the `OpenCV` library for video capture and the `Pyzbar` library for QR code decoding.
> - Supports various QR code formats.
> 
> * **Read** the ***readme.md*** given inside the folder and try it out ! ***:-)***
> 
> 
> ### Header
> * point1
> * point 2
> * point 3
> * point 4
> *  point 5
> 
> Dont add any other header non header or any words in between and keep the points as it is that is using * no - no ` .
> 
> 
> 

I'm having mid term exams now 😭

2024-10-19 11:28 UTC, Anuraj-IND commented
done, btw you forgot to add label

2024-10-19 11:31 UTC, Anuraj-IND commented
@PreyumKr ig its done now

2024-10-19 11:37 UTC, Anuraj-IND commented
response please i need to study now so see if its final nor what

2024-10-19 12:03 UTC, PreyumKr commented on README.md
> +
why this space but its ok. Also It looks the file is not synced to the latest readme. Its still showing the old layout but showing only the new lines as newly added so maybe I'll merge and check

2024-10-19 12:04 UTC, PreyumKr approved these changes
There is space and the readme is older than the latest that's there in the main

2024-10-19 12:04 UTC, merged

2024-10-19 12:36 UTC, Anuraj-IND commented
@PreyumKr you forgot to add label QwQ

2024-10-19 18:46 UTC, PreyumKr commented
Okay I'll add the tag but that's not really a must have. It takes time for a maintainer to approve the PR even with or without the tag. I have all four approved and waiting for review and I don't use the tag for my own PRs.